//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace БИПиТ11
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int IdC { get; set; }

        [Required]
        [RegularExpression(@"([А-ЯA-Z][а-яa-zА-ЯA-Z\s]+)", ErrorMessage = "Некорректное поле Клиент. Корректный формат: Иванов Иван")]
        public string Client1 { get; set; }

        [Required]
        [RegularExpression(@"([8][0-9]{10})", ErrorMessage = "Некорректное поле Телефон. Корректный формат: 8XXXXXXXXXX")]
        public long Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
